from django.urls import path
from . import views
# 从home.views导入QC报表和微信认证相关的视图（通过__init__.py统一管理）
from .views import (
    # QC报表API类
    DongtaiQCReportAPI, DayuanQCReportAPI, XinghuiQCReportAPI, ChangfuQCReportAPI,
    YuantongQCReportAPI, Yuantong2QCReportAPI, Xinghui2QCReportAPI,
    # QC报表视图函数和导出函数
    qc_report, dayuan_report, dongtai_report, yuantong_report, yuantong2_report,
    xinghui_report, xinghui2_report, changfu_report,
    dayuan_report_edit, dayuan_report_history, dayuan_report_import_excel, dayuan_report_download_template,
    dongtai_report_edit, dongtai_report_history, dongtai_report_import_excel, dongtai_report_download_template,
    yuantong_report_edit, yuantong_report_history, yuantong_report_import_excel, yuantong_report_download_template,
    yuantong2_report_edit, yuantong2_report_history, yuantong2_report_import_excel, yuantong2_report_download_template,
    xinghui_report_edit, xinghui_report_history, xinghui_report_import_excel, xinghui_report_download_template,
    xinghui2_report_edit, xinghui2_report_history, xinghui2_report_import_excel, xinghui2_report_download_template,
    changfu_report_edit, changfu_report_history, changfu_report_import_excel, changfu_report_download_template,
    export_dongtai_report_excel, export_dongtai_yesterday_production, export_dongtai_today_production,
    export_dayuan_report_excel, export_dayuan_yesterday_production, export_dayuan_today_production,
    export_yuantong_report_excel, export_yuantong_yesterday_production, export_yuantong_today_production,
    export_yuantong2_report_excel, export_yuantong2_yesterday_production, export_yuantong2_today_production,
    export_xinghui_report_excel, export_xinghui_yesterday_production, export_xinghui_today_production,
    export_changfu_report_excel, export_changfu_yesterday_production, export_changfu_today_production,
    export_xinghui2_report_excel, export_xinghui2_yesterday_production, export_xinghui2_today_production,
    # 导入缺失的函数
    yuantong_report_download_template, yuantong_report_import_excel,
    yuantong2_report_download_template, yuantong2_report_import_excel,
    xinghui2_report_download_template, xinghui2_report_import_excel,
    # 微信认证
    wechat_login, WeChatUserListAPI,
)

urlpatterns = [

    path('api/permissions/', views.PermissionAPI.as_view(), name='permission_api'),
    path('api/wechat-users/', WeChatUserListAPI.as_view(), name='wechat_user_list_api'),
    path('api/wechat_users/', WeChatUserListAPI.as_view(), name='wechat_user_list_api_underscore'),
    path('api/password-login/', views.PasswordLoginAPI.as_view(), name='password_login_api'),
    path('production/history/edit/<str:fnumber>/', views.ProductionHistoryView.as_view(), name='production_history_edit'),
    path('', views.IndexView.as_view(), name='index'),
    path('home/', views.HomeView.as_view(), name='home'),
    path('login/', wechat_login, name='login'),
    path('home/system/parameter-config/', views.ParameterConfigView.as_view(), name='parameter_config'),
    path('system/parameter-config/', views.ParameterConfigView.as_view(), name='parameter_config'),
    path('api/parameters/<str:param_id>/', views.get_parameter, name='get_parameter'),
    path('api/report-parameters/<str:param_id>/', views.get_report_parameter, name='get_report_parameter'),
    path('api/parameters/', views.ParameterConfigView.as_view(), name='parameter_api'),
    path('system/user-management/', views.user_management, name='user_management'),
    path('system/operation-log/', views.operation_log_view, name='operation_log'),
    path('api/user-info/', views.user_info_api, name='user_info_api'),
    path('api/operation-log/', views.operation_log_api, name='operation_log_api'),
    path('debug/user-info/', views.debug_user_info, name='debug_user_info'),
    path('test/qc-report/', views.qc_test_report_page, name='qc_test_report_page'),
    path('api/user-management/', views.UserManagementAPI.as_view(), name='user_management_api'),
    path('api/user-management/<int:user_id>/', views.UserManagementAPI.as_view(), name='user_management_detail_api'),
    path('api/user-management/<int:user_id>/reset-password/', views.UserPasswordResetAPI.as_view(), name='user_password_reset_api'),
    
    # 原始API路径
    # path('api/material-mappings/', views.MaterialMappingAPI.as_view(), name='material_mapping_api'),
    # path('api/material-mappings/<int:material_id>/', views.MaterialMappingAPI.as_view(), name='material_mapping_detail_api'),
    # path('api/inventory-orgs/', views.InventoryOrgAPI.as_view(), name='inventory_org_api'),
    # path('api/inventory-orgs/<int:org_id>/', views.InventoryOrgAPI.as_view(), name='inventory_org_detail_api'),
    # path('api/warehouse-mappings/', views.WarehouseMappingAPI.as_view(), name='warehouse_mapping_api'),
    # path('api/warehouse-mappings/<int:warehouse_id>/', views.WarehouseMappingAPI.as_view(), name='warehouse_mapping_detail_api'),
    # path('api/cost-center-mappings/', views.CostCenterMappingAPI.as_view(), name='cost_center_mapping_api'),
    # path('api/cost-center-mappings/<int:cost_center_id>/', views.CostCenterMappingAPI.as_view(), name='cost_center_mapping_detail_api'),
    # path('api/cost-object-mappings/', views.CostObjectMappingAPI.as_view(), name='cost_object_mapping_api'),
    # path('api/cost-object-mappings/<int:cost_object_id>/', views.CostObjectMappingAPI.as_view(), name='cost_object_mapping_detail_api'),
    
    # 备用API路径（匹配前端JavaScript使用的路径）
    path('api/inventory-org/', views.InventoryOrgAPI.as_view(), name='inventory_org_api_alt'),
    path('api/inventory-org/<int:org_id>/', views.InventoryOrgAPI.as_view(), name='inventory_org_detail_api_alt'),
    path('api/materials/', views.MaterialMappingAPI.as_view(), name='material_mapping_api_alt'),
    path('api/materials/<int:material_id>/', views.MaterialMappingAPI.as_view(), name='material_mapping_detail_api_alt'),
    path('api/warehouses/', views.WarehouseMappingAPI.as_view(), name='warehouse_mapping_api_alt'),
    path('api/warehouses/<int:warehouse_id>/', views.WarehouseMappingAPI.as_view(), name='warehouse_mapping_detail_api_alt'),
    path('api/cost-centers/', views.CostCenterMappingAPI.as_view(), name='cost_center_mapping_api_alt'),
    path('api/cost-centers/<int:cost_center_id>/', views.CostCenterMappingAPI.as_view(), name='cost_center_mapping_detail_api_alt'),
    path('api/cost-objects/', views.CostObjectMappingAPI.as_view(), name='cost_object_mapping_api_alt'),
    path('api/cost-objects/<int:cost_object_id>/', views.CostObjectMappingAPI.as_view(), name='cost_object_mapping_detail_api_alt'),
    
    path('api/water-deduction-rates/', views.WaterDeductionRateAPI.as_view(), name='water_deduction_rate_api'),
    path('api/water-deduction-rates/<int:rate_id>/', views.WaterDeductionRateAPI.as_view(), name='water_deduction_rate_detail_api'),
    path('api/operation-objects/', views.OperationObjectAPI.as_view(), name='operation_object_api'),
    path('api/operation-objects/<int:object_id>/', views.OperationObjectAPI.as_view(), name='operation_object_detail_api'),
    path('api/product-models/', views.ProductModelAPI.as_view(), name='product_model_api'),
    path('api/product-models/<int:model_id>/', views.ProductModelAPI.as_view(), name='product_model_detail_api'),
    path('api/product-models/suggest/', views.product_model_suggest, name='product_model_suggest'),
    path('api/packagings/', views.PackagingAPI.as_view(), name='packaging_api'),
    path('api/packagings/<int:packaging_id>/', views.PackagingAPI.as_view(), name='packaging_detail_api'),
    path('api/packagings/suggest/', views.packaging_suggest, name='packaging_suggest'),
    path('system/packaging/', views.packaging, name='packaging'),
    path('system/product-model/', views.product_model, name='product_model'),
    path('api/user-favorite/', views.UserFavoriteAPI.as_view(), name='user_favorite_api'),
    
    # 生产管理路由
    path('api/raw-soil-storage/query/', views.RawSoilStorageQueryAPI.as_view(), name='raw_soil_storage_query_api'),
    path('production/raw-soil-storage/', views.RawSoilStorageView.as_view(), name='raw_soil_storage'),
    path('production/raw-soil-storage/<str:fnumber>/edit/', views.RawSoilStorageView.as_view(), name='raw_soil_storage_edit'),
    path('production/history/', views.ProductionHistoryView.as_view(), name='production_history'),
    path('production/raw-soil-storage/<str:fnumber>/delete/', views.RawSoilStorageView.as_view(), name='raw_soil_storage_delete'),
    path('qc_report/', qc_report, name='qc_report'),
    path('dongtai_report/', dongtai_report, name='dongtai_report'),
    path('dongtai_report/history/', dongtai_report_history, name='dongtai_report_history'),
    path('dongtai_report/export_excel/', export_dongtai_report_excel, name='export_dongtai_report_excel'),
    path('dongtai_report/download_template/', dongtai_report_download_template, name='dongtai_report_download_template'),
    path('dongtai_report/import_excel/', dongtai_report_import_excel, name='dongtai_report_import_excel'),
    path('dongtai_report/export_yesterday_production/', export_dongtai_yesterday_production, name='export_dongtai_yesterday_production'),
    path('dongtai_report/export_today_production/', export_dongtai_today_production, name='export_dongtai_today_production'),
    path('dongtai-report-edit/<int:report_id>/', dongtai_report_edit, name='dongtai_report_edit'),
    path('dayuan_report/', dayuan_report, name='dayuan_report'),
    path('dayuan_report/history/', dayuan_report_history, name='dayuan_report_history'),
    path('dayuan_report/export_excel/', export_dayuan_report_excel, name='export_dayuan_report_excel'),
    path('dayuan_report/download_template/', dayuan_report_download_template, name='dayuan_report_download_template'),
    path('dayuan_report/import_excel/', dayuan_report_import_excel, name='dayuan_report_import_excel'),
    path('dayuan_report/export_yesterday_production/', export_dayuan_yesterday_production, name='export_dayuan_yesterday_production'),
    path('dayuan_report/export_today_production/', export_dayuan_today_production, name='export_dayuan_today_production'),
    path('dayuan-report-edit/<int:report_id>/', dayuan_report_edit, name='dayuan_report_edit'),
    path('xinghui_report/', xinghui_report, name='xinghui_report'),
    path('xinghui_report/history/', xinghui_report_history, name='xinghui_report_history'),
    path('xinghui_report/export_excel/', export_xinghui_report_excel, name='export_xinghui_report_excel'),
    path('xinghui_report/download_template/', xinghui_report_download_template, name='xinghui_report_download_template'),
    path('xinghui_report/import_excel/', xinghui_report_import_excel, name='xinghui_report_import_excel'),
    path('xinghui_report/export_yesterday_production/', export_xinghui_yesterday_production, name='export_xinghui_yesterday_production'),
    path('xinghui_report/export_today_production/', export_xinghui_today_production, name='export_xinghui_today_production'),
    path('xinghui-report-edit/<int:report_id>/', xinghui_report_edit, name='xinghui_report_edit'),
    path('changfu_report/', changfu_report, name='changfu_report'),
    path('changfu_report/history/', changfu_report_history, name='changfu_report_history'),
    path('changfu_report/export_excel/', export_changfu_report_excel, name='export_changfu_report_excel'),
    path('changfu_report/download_template/', changfu_report_download_template, name='changfu_report_download_template'),
    path('changfu_report/import_excel/', changfu_report_import_excel, name='changfu_report_import_excel'),
    path('changfu_report/export_yesterday_production/', export_changfu_yesterday_production, name='export_changfu_yesterday_production'),
    path('changfu_report/export_today_production/', export_changfu_today_production, name='export_changfu_today_production'),
    path('changfu-report-edit/<int:report_id>/', changfu_report_edit, name='changfu_report_edit'),
    path('changfu_report/debug/', views.changfu_debug, name='changfu_debug'),
    path('changfu_report/debug_simple/', views.changfu_debug_simple, name='changfu_debug_simple'),
    path('yuantong_report/', yuantong_report, name='yuantong_report'),
    path('yuantong_report/history/', yuantong_report_history, name='yuantong_report_history'),
    path('yuantong_report/export_excel/', export_yuantong_report_excel, name='export_yuantong_report_excel'),
    path('yuantong_report/download_template/', yuantong_report_download_template, name='yuantong_report_download_template'),
    path('yuantong_report/import_excel/', yuantong_report_import_excel, name='yuantong_report_import_excel'),
    path('yuantong_report/export_yesterday_production/', export_yuantong_yesterday_production, name='export_yuantong_yesterday_production'),
    path('yuantong_report/export_today_production/', export_yuantong_today_production, name='export_yuantong_today_production'),

    path('yuantong-report-edit/<int:report_id>/', yuantong_report_edit, name='yuantong_report_edit'),
    path('xinghui2_report/', xinghui2_report, name='xinghui2_report'),
    path('xinghui2_report/history/', xinghui2_report_history, name='xinghui2_report_history'),
    path('xinghui2_report/export_excel/', export_xinghui2_report_excel, name='export_xinghui2_report_excel'),
    path('xinghui2_report/download_template/', xinghui2_report_download_template, name='xinghui2_report_download_template'),
    path('xinghui2_report/import_excel/', xinghui2_report_import_excel, name='xinghui2_report_import_excel'),
    path('xinghui2_report/export_yesterday_production/', export_xinghui2_yesterday_production, name='export_xinghui2_yesterday_production'),
    path('xinghui2_report/export_today_production/', export_xinghui2_today_production, name='export_xinghui2_today_production'),
    path('xinghui2-report-edit/<int:report_id>/', xinghui2_report_edit, name='xinghui2_report_edit'),
    path('yuantong2_report/', yuantong2_report, name='yuantong2_report'),
    path('yuantong2_report/history/', yuantong2_report_history, name='yuantong2_report_history'),
    path('yuantong2_report/download_template/', yuantong2_report_download_template, name='yuantong2_report_download_template'),
    path('yuantong2_report/import_excel/', yuantong2_report_import_excel, name='yuantong2_report_import_excel'),
    path('yuantong2_report/export_excel/', export_yuantong2_report_excel, name='export_yuantong2_report_excel'),
    path('yuantong2_report/export_yesterday_production/', export_yuantong2_yesterday_production, name='export_yuantong2_yesterday_production'),
    path('yuantong2_report/export_today_production/', export_yuantong2_today_production, name='export_yuantong2_today_production'),
    path('yuantong2-report-edit/<int:report_id>/', yuantong2_report_edit, name='yuantong2_report_edit'),
    
    # 权限设置管理
    path('admin/permission-settings/', views.admin_permission_settings, name='admin_permission_settings'),
    path('admin/simple-permission-config/', views.simple_permission_config, name='simple_permission_config'),
    path('admin/debug-user-permissions/', views.debug_user_permissions_page, name='debug_user_permissions_page'),
    path('admin/user-permission-guide/', views.user_permission_guide_page, name='user_permission_guide_page'),
    path('system/user-permissions/', views.simple_user_permissions_page, name='simple_user_permissions_page'),
    path('admin/user-permissions/', views.user_permission_management, name='user_permission_management'),
    path('admin/api/update-user-permissions/', views.update_user_permissions, name='update_user_permissions'),
    path('admin/api/get-user-permissions/', views.get_user_permissions, name='get_user_permissions'),

    path('api/dongtai-report/', DongtaiQCReportAPI.as_view(), name='dongtai_report_api'),
    path('api/dongtai-report/<int:report_id>/', DongtaiQCReportAPI.as_view(), name='dongtai_report_detail_api'),
    path('api/dayuan-report/', DayuanQCReportAPI.as_view(), name='dayuan_report_api'),
    path('api/dayuan-report/<int:report_id>/', DayuanQCReportAPI.as_view(), name='dayuan_report_detail_api'),
    path('api/xinghui-report/', XinghuiQCReportAPI.as_view(), name='xinghui_report_api'),
    path('api/xinghui-report/<int:report_id>/', XinghuiQCReportAPI.as_view(), name='xinghui_report_detail_api'),    
    path('api/changfu-report/', ChangfuQCReportAPI.as_view(), name='changfu_report_api'),
    path('api/changfu-report/<int:report_id>/', ChangfuQCReportAPI.as_view(), name='changfu_report_detail_api'),
    path('api/yuantong-report/', YuantongQCReportAPI.as_view(), name='yuantong_report_api'),
    path('api/yuantong-report/<int:report_id>/', YuantongQCReportAPI.as_view(), name='yuantong_report_detail_api'),
    path('api/xinghui2-report/', Xinghui2QCReportAPI.as_view(), name='xinghui2_report_api'),
    path('api/xinghui2-report/<int:report_id>/', Xinghui2QCReportAPI.as_view(), name='xinghui2_report_detail_api'),
    path('api/yuantong2-report/', Yuantong2QCReportAPI.as_view(), name='yuantong2_report_api'),
    path('api/yuantong2-report/<int:report_id>/', Yuantong2QCReportAPI.as_view(), name='yuantong2_report_detail_api'),
    
    # RBAC权限管理路由
    path('system/rbac-management/', views.rbac_management, name='rbac_management'),
    path('api/rbac/roles/', views.RBACRoleAPI.as_view(), name='rbac_role_api'),
    path('api/rbac/roles/<int:role_id>/', views.RBACRoleAPI.as_view(), name='rbac_role_detail_api'),
    path('api/rbac/roles/<int:role_id>/permissions/', views.RBACRolePermissionAPI.as_view(), name='rbac_role_permission_api'),
    path('api/rbac/permissions/', views.RBACPermissionAPI.as_view(), name='rbac_permission_api'),
    path('api/rbac/permissions/<int:permission_id>/', views.RBACPermissionAPI.as_view(), name='rbac_permission_detail_api'),
    path('api/rbac/user-roles/', views.RBACUserRoleAPI.as_view(), name='rbac_user_role_api'),
    path('api/rbac/user-roles/<int:user_role_id>/', views.RBACUserRoleAPI.as_view(), name='rbac_user_role_detail_api'),
    
    # 操作日志相关API
    path('api/log-view-operation/', views.log_view_operation_api, name='log_view_operation_api'),

]
