"""
Django settings for yuantong project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# 加载环境变量
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# 仅开发时可用默认值；生产环境必须在 .env 中设置 SECRET_KEY
SECRET_KEY = os.environ.get('SECRET_KEY', '') or 'dev-insecure-change-me'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True').lower() == 'true'

# 从环境变量获取允许的主机列表
ALLOWED_HOSTS_STR = os.environ.get('ALLOWED_HOSTS', 'jilinyuantong.top,www.jilinyuantong.top,localhost,127.0.0.1,123.249.75.132,testserver')
ALLOWED_HOSTS = [host.strip() for host in ALLOWED_HOSTS_STR.split(',') if host.strip()]

# 生产环境安全配置
if not DEBUG:
    # HTTPS 安全配置
    SECURE_SSL_REDIRECT = os.environ.get('SECURE_SSL_REDIRECT', 'True').lower() == 'true'
    SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', '31536000'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = os.environ.get('SECURE_HSTS_INCLUDE_SUBDOMAINS', 'True').lower() == 'true'
    SECURE_HSTS_PRELOAD = os.environ.get('SECURE_HSTS_PRELOAD', 'True').lower() == 'true'
    SECURE_CONTENT_TYPE_NOSNIFF = os.environ.get('SECURE_CONTENT_TYPE_NOSNIFF', 'True').lower() == 'true'
    SECURE_BROWSER_XSS_FILTER = os.environ.get('SECURE_BROWSER_XSS_FILTER', 'True').lower() == 'true'
    X_FRAME_OPTIONS = os.environ.get('X_FRAME_OPTIONS', 'SAMEORIGIN')
    
    # Session 安全配置
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True
    CSRF_COOKIE_HTTPONLY = True
    SESSION_COOKIE_SAMESITE = 'Lax'
    CSRF_COOKIE_SAMESITE = 'Lax'
else:
    # 开发环境配置
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False

# Application definition

INSTALLED_APPS = [
    'wechat_auth.apps.WechatAuthConfig',
    'audit',
    'django_celery_beat',
    'home',
    'system',
    'tasks',
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'corsheaders',
]


MIDDLEWARE = [
    'audit.middleware.AuditMiddleware',
    'core.middleware.MobileDetectionMiddleware',
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    'corsheaders.middleware.CorsMiddleware',
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "yuantong.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates']
        ,
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "yuantong.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('DB_NAME', 'yuantong'),
        'USER': os.environ.get('DB_USER', 'root'),
        'PASSWORD': os.environ.get('DB_PASSWORD', ''),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '3306'),
        'OPTIONS': {
            'charset': 'utf8mb4',
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {
            "min_length": 12,
        }
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "zh-hans"

TIME_ZONE = "Asia/Shanghai"

USE_I18N = True
USE_TZ = True

# 添加中文支持
LANGUAGES = [
    ('zh-hans', '简体中文'),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# EAS API Configuration（从环境变量读取，勿提交真实地址）
EAS_API_HOST = os.environ.get('EAS_API_HOST', '')
EAS_API_PATH_ADD = os.environ.get('EAS_API_PATH_ADD', '/geteasdata/addManufactureRec')
EAS_API_PATH_UPDATE = os.environ.get('EAS_API_PATH_UPDATE', '/geteasdata/upManufactureRec')
EAS_API_PATH_DELETE = os.environ.get('EAS_API_PATH_DELETE', '/geteasdata/delManufactureRec')
EAS_API_PATH_GET = os.environ.get('EAS_API_PATH_GET', '/geteasdata/getManufactureRec')

# WeChat Configuration - 仅从环境变量读取，不写默认值
# WECHAT_CORP_SECRET 兼容 WECHAT_APP_SECRET（应用密钥，多数场景下可通用）
WECHAT_CORP_ID = os.environ.get('WECHAT_CORP_ID', '')
WECHAT_CORP_SECRET = os.environ.get('WECHAT_CORP_SECRET', '') or os.environ.get('WECHAT_APP_SECRET', '')
WECHAT_AGENT_ID = os.environ.get('WECHAT_AGENT_ID', '')
REDIRECT_URI = os.environ.get('REDIRECT_URI')

# 生产环境必须配置企业微信
if not DEBUG and not all([WECHAT_CORP_ID, WECHAT_CORP_SECRET, WECHAT_AGENT_ID]):
    raise ValueError("生产环境必须设置环境变量: WECHAT_CORP_ID, WECHAT_CORP_SECRET(或WECHAT_APP_SECRET), WECHAT_AGENT_ID")

# Redis配置 (用于缓存和会话存储)
REDIS_URL = os.environ.get('REDIS_URL', 'redis://localhost:6379/0')
CACHE_REDIS_URL = os.environ.get('CACHE_REDIS_URL', 'redis://localhost:6379/1')

# 缓存配置 - 临时使用本地内存缓存避免Redis问题
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
        'TIMEOUT': 300,  # 5分钟默认缓存时间
        'KEY_PREFIX': 'yuantong_cache',
        'VERSION': 1,
    }
}

# 生产环境暂时使用数据库session而不是Redis session
if not DEBUG:
    # 明确设置使用数据库session，避免Redis配置问题
    SESSION_ENGINE = 'django.contrib.sessions.backends.db'
    # 暂时禁用Redis session，使用数据库session避免跨进程问题
    # SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
    # SESSION_CACHE_ALIAS = 'default'
else:
    # 开发环境也使用数据库session
    SESSION_ENGINE = 'django.contrib.sessions.backends.db'

# 邮件配置 (用于错误通知)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'localhost')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() == 'true'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'noreply@jilinyuantong.top')
SERVER_EMAIL = os.environ.get('SERVER_EMAIL', 'server@jilinyuantong.top')

# 管理员邮箱配置
ADMINS_STR = os.environ.get('ADMINS', '')
if ADMINS_STR:
    ADMINS = [('Admin', email.strip()) for email in ADMINS_STR.split(',') if email.strip()]
else:
    ADMINS = []

# Login settings
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'

# Session settings
SESSION_COOKIE_AGE = 86400  # 24 hours in seconds (增加到24小时)
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # 不要在浏览器关闭时立即过期
SESSION_COOKIE_HTTPONLY = True  # Prevent JavaScript access to session cookie
SESSION_COOKIE_SAMESITE = 'Lax'  # 设置为Lax兼容性更好
SESSION_SAVE_EVERY_REQUEST = True  # Update session on every request
SESSION_COOKIE_SECURE = not DEBUG  # HTTPS环境下设为True，开发环境设为False
SESSION_COOKIE_DOMAIN = None  # 让Django自动处理域名

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '[{levelname}] {asctime} {message}',
            'style': '{',
        },
        'django_format': {
            'format': '[{levelname}] {asctime} {name} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'debug_file': {
            'class': 'logging.FileHandler',
            'filename': str(BASE_DIR / 'logs' / 'debug.log'),
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
        'django_file': {
            'class': 'logging.FileHandler',
            'filename': str(BASE_DIR / 'logs' / 'django.log'),
            'formatter': 'django_format',
            'encoding': 'utf-8',
        },
        'error_file': {
            'class': 'logging.FileHandler',
            'filename': str(BASE_DIR / 'logs' / 'error.log'),
            'formatter': 'verbose',
            'encoding': 'utf-8',
            'level': 'ERROR',
        },
    },
    'loggers': {
        'home': {  # home应用的日志记录器
            'handlers': ['console', 'debug_file'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
        'api': {  # api应用的日志记录器
            'handlers': ['console', 'debug_file'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
        'django': {  # Django框架日志
            'handlers': ['console', 'django_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {  # Django请求日志
            'handlers': ['django_file', 'error_file'],
            'level': 'WARNING',
            'propagate': False,
        },
        'django.security': {  # Django安全日志
            'handlers': ['django_file', 'error_file'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console', 'debug_file'],
        'level': 'DEBUG' if DEBUG else 'INFO',
    },
}

APPEND_SLASH=False

# CSRF 和 CORS 配置 - 根据环境动态设置
if DEBUG:
    CSRF_TRUSTED_ORIGINS = [
        "http://localhost:8000",
        "http://127.0.0.1:8000",
        "https://jilinyuantong.top",
        "https://www.jilinyuantong.top",
    ]
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:8000",
        "http://127.0.0.1:8000",
        "https://jilinyuantong.top",
        "https://www.jilinyuantong.top",
    ]
else:
    # 生产环境需要配置实际的域名
    CSRF_TRUSTED_ORIGINS = [f"https://{host}" for host in ALLOWED_HOSTS if host not in ['localhost', '127.0.0.1']]
    CORS_ALLOWED_ORIGINS = [f"https://{host}" for host in ALLOWED_HOSTS if host not in ['localhost', '127.0.0.1']]

# 生产环境额外安全配置
if not DEBUG:
    # 禁用不安全的HTTP方法
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    
    # 限制文件上传大小
    FILE_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB
    DATA_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB
    
    # 设置更严格的密码验证
    AUTH_PASSWORD_VALIDATORS = [
        {
            "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
        },
        {
            "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
            "OPTIONS": {
                "min_length": 12,
            }
        },
        {
            "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
        },
        {
            "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
        },
    ]
else:
    # 开发环境使用较宽松的密码验证
    AUTH_PASSWORD_VALIDATORS = [
        {
            "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
        },
        {
            "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        },
        {
            "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
        },
        {
            "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
        },
    ]

# Celery配置
CELERY_BROKER_URL = os.environ.get('REDIS_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('REDIS_URL', 'redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Shanghai'
CELERY_ENABLE_UTC = True
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# 队列配置
CELERY_TASK_DEFAULT_QUEUE = 'default'
CELERY_TASK_ROUTES = {
    'tasks.tasks.*': {'queue': 'default'},
}
