# Generated by Django 5.1.6 on 2025-02-21 05:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_materialmapping_delete_inventoryorganization"),
    ]

    operations = [
        migrations.CreateModel(
            name="WarehouseMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("warehouse_code", models.CharField(max_length=50, unique=True)),
                ("warehouse_name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "warehouse_mapping",
            },
        ),
    ]
