# Generated by Django 5.1.6 on 2025-02-25 03:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_warehousemapping"),
    ]

    operations = [
        migrations.CreateModel(
            name="CostCenterMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cost_center_code", models.CharField(max_length=50, unique=True)),
                ("cost_center_name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "cost_center_mapping",
            },
        ),
    ]
