# Generated by Django 5.1.6 on 2025-03-26 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_costobjectmapping"),
    ]

    operations = [
        migrations.CreateModel(
            name="WaterDeductionRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rate", models.DecimalField(decimal_places=2, max_digits=5)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "inventory_org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="water_deduction_rates",
                        to="home.inventoryorg",
                    ),
                ),
            ],
            options={
                "db_table": "water_deduction_rate",
                "unique_together": {("inventory_org",)},
            },
        ),
    ]
