# Generated by Django 5.1.6 on 2025-04-08 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0006_waterdeductionrate"),
    ]

    operations = [
        migrations.CreateModel(
            name="OperationObject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=100)),
                (
                    "water_deduction_rate",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cost_center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operation_objects",
                        to="home.costcentermapping",
                    ),
                ),
                (
                    "cost_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operation_objects",
                        to="home.costobjectmapping",
                    ),
                ),
                (
                    "inventory_org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operation_objects",
                        to="home.inventoryorg",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operation_objects",
                        to="home.warehousemapping",
                    ),
                ),
            ],
            options={
                "db_table": "operation_object",
                "unique_together": {
                    (
                        "user_id",
                        "inventory_org",
                        "warehouse",
                        "cost_center",
                        "cost_object",
                    )
                },
            },
        ),
    ]
