# Generated by Django 5.1.6 on 2025-04-08 11:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0007_operationobject"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OperationObject",
        ),
    ]
