# Generated by Django 5.1.6 on 2025-04-10 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0008_delete_operationobject"),
    ]

    operations = [
        migrations.CreateModel(
            name="OperationObject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=50, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cost_center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operation_objects",
                        to="home.costcentermapping",
                    ),
                ),
                (
                    "cost_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operation_objects",
                        to="home.costobjectmapping",
                    ),
                ),
                (
                    "inventory_org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operation_objects",
                        to="home.inventoryorg",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operation_objects",
                        to="home.warehousemapping",
                    ),
                ),
            ],
            options={
                "db_table": "operation_object",
                "unique_together": {("inventory_org",)},
            },
        ),
    ]
