# Generated by Django 5.1.6 on 2025-04-10 06:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0009_operationobject"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="operationobject",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="operationobject",
            name="rate",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="operationobject",
            name="user_id",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name="operationobject",
            unique_together={
                ("user_id", "inventory_org", "warehouse", "cost_center", "cost_object")
            },
        ),
    ]
