# Generated by Django 5.1.6 on 2025-04-28 07:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0010_alter_operationobject_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DayuanQCReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="日期")),
                ("time", models.TimeField(verbose_name="时间")),
                (
                    "moisture_after_drying",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="干燥后原土水分(%)"
                    ),
                ),
                (
                    "alkali_content",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="入窑前碱含量(%)"
                    ),
                ),
                (
                    "flux",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="助溶剂添加比例",
                    ),
                ),
                ("grade", models.CharField(max_length=50, verbose_name="产品型号")),
                (
                    "permeability",
                    models.DecimalField(
                        decimal_places=4, max_digits=10, verbose_name="远通渗透率(Darcy)"
                    ),
                ),
                (
                    "permeability_long",
                    models.DecimalField(
                        decimal_places=4, max_digits=10, verbose_name="长富渗透率(Darcy)"
                    ),
                ),
                (
                    "wet_cake_density",
                    models.DecimalField(
                        decimal_places=3, max_digits=5, verbose_name="饼密度(g/cm3)"
                    ),
                ),
                (
                    "sieving_14m",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="+14M",
                    ),
                ),
                (
                    "sieving_30m",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="+30M",
                    ),
                ),
                (
                    "sieving_40m",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="+40M",
                    ),
                ),
                (
                    "sieving_150m",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="+150M",
                    ),
                ),
                (
                    "sieving_200m",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="+200M",
                    ),
                ),
                (
                    "sieving_325m",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="+325M",
                    ),
                ),
                (
                    "brightness",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="白度"
                    ),
                ),
                (
                    "swirl",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="涡值(cm)"
                    ),
                ),
                (
                    "odor",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="气味"
                    ),
                ),
                (
                    "conductance",
                    models.DecimalField(
                        decimal_places=2, max_digits=7, verbose_name="⚡电导值(ms/cm)"
                    ),
                ),
                (
                    "ph",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="pH"
                    ),
                ),
                (
                    "moisture",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="水分(%)"
                    ),
                ),
                ("bags", models.IntegerField(verbose_name="袋数")),
                ("ipkp_code", models.CharField(max_length=50, verbose_name="包装类型")),
                (
                    "tons",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="吨"
                    ),
                ),
                ("lot", models.CharField(max_length=50, verbose_name="LOT批号")),
                ("squad", models.CharField(max_length=50, verbose_name="班组")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "大塬QC报表",
                "verbose_name_plural": "大塬QC报表",
                "db_table": "dayuan_qc_report",
                "ordering": ["-date", "-time"],
            },
        ),
        migrations.CreateModel(
            name="DongtaiQCReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="检测日期")),
                ("material_code", models.CharField(max_length=50, verbose_name="物料编码")),
                (
                    "material_name",
                    models.CharField(max_length=100, verbose_name="物料名称"),
                ),
                ("batch_number", models.CharField(max_length=50, verbose_name="批次号")),
                ("test_item", models.CharField(max_length=100, verbose_name="检测项目")),
                ("test_result", models.CharField(max_length=200, verbose_name="检测结果")),
                ("tester", models.CharField(max_length=50, verbose_name="检测人")),
                ("remark", models.TextField(blank=True, null=True, verbose_name="备注")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "东泰QC报表",
                "verbose_name_plural": "东泰QC报表",
                "db_table": "dongtai_qc_report",
            },
        ),
    ]
