# Generated by Django 5.1.6 on 2025-04-29 08:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0011_dayuanqcreport_dongtaiqcreport"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="产品型号名称"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "产品型号",
                "verbose_name_plural": "产品型号",
                "ordering": ["-created_at"],
            },
        ),
    ]
