# Generated by Django 5.1.6 on 2025-04-30 09:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0012_productmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="Packaging",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="包装物名称"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "包装物",
                "verbose_name_plural": "包装物",
                "ordering": ["-created_at"],
            },
        ),
    ]
