# Generated by Django 5.1.6 on 2025-05-07 08:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0013_packaging"),
    ]

    operations = [
        migrations.AddField(
            model_name="dayuanqcreport",
            name="sieving_80m",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="+80M",
            ),
        ),
    ]
