# Generated by Django 5.1.6 on 2025-05-07 08:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0014_dayuanqcreport_sieving_80m"),
    ]

    operations = [
        migrations.AddField(
            model_name="dayuanqcreport",
            name="al_ion",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=7,
                null=True,
                verbose_name="铝离子(mg/kg)",
            ),
        ),
        migrations.AddField(
            model_name="dayuanqcreport",
            name="ca_ion",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=7,
                null=True,
                verbose_name="钙离子(mg/kg)",
            ),
        ),
        migrations.AddField(
            model_name="dayuanqcreport",
            name="fe_ion",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=7,
                null=True,
                verbose_name="铁离子(mg/kg)",
            ),
        ),
    ]
