# Generated by Django 5.1.6 on 2025-05-07 08:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0015_dayuanqcreport_al_ion_dayuanqcreport_ca_ion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dayuanqcreport",
            name="oil_absorption",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="吸油率(%)",
            ),
        ),
        migrations.AddField(
            model_name="dayuanqcreport",
            name="remark",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="备注"
            ),
        ),
        migrations.AddField(
            model_name="dayuanqcreport",
            name="water_absorption",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="吸水率(%)",
            ),
        ),
    ]
