# Generated by Django 5.1.6 on 2025-05-15 02:30

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0017_userfavorite"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dayuanqcreport",
            options={
                "ordering": ["-date", "-created_at"],
                "verbose_name": "大塬QC报表",
                "verbose_name_plural": "大塬QC报表",
            },
        ),
        migrations.RemoveField(
            model_name="dayuanqcreport",
            name="grade",
        ),
        migrations.RemoveField(
            model_name="dayuanqcreport",
            name="ipkp_code",
        ),
        migrations.RemoveField(
            model_name="dayuanqcreport",
            name="lot",
        ),
        migrations.RemoveField(
            model_name="dayuanqcreport",
            name="odor",
        ),
        migrations.RemoveField(
            model_name="dayuanqcreport",
            name="remark",
        ),
        migrations.RemoveField(
            model_name="dayuanqcreport",
            name="sieving_80m",
        ),
        migrations.RemoveField(
            model_name="dayuanqcreport",
            name="squad",
        ),
        migrations.RemoveField(
            model_name="dayuanqcreport",
            name="swirl",
        ),
        migrations.RemoveField(
            model_name="dayuanqcreport",
            name="time",
        ),
        migrations.AddField(
            model_name="dayuanqcreport",
            name="product_name",
            field=models.CharField(default="", max_length=100, verbose_name="产品名称"),
        ),
        migrations.AddField(
            model_name="dayuanqcreport",
            name="remarks",
            field=models.TextField(blank=True, verbose_name="备注"),
        ),
        migrations.AddField(
            model_name="dayuanqcreport",
            name="shift",
            field=models.CharField(default="", max_length=10, verbose_name="班次"),
        ),
        migrations.AddField(
            model_name="dayuanqcreport",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dayuan_reports",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AddField(
            model_name="dayuanqcreport",
            name="username",
            field=models.CharField(max_length=150, null=True, verbose_name="用户名"),
        ),
        migrations.AlterField(
            model_name="dayuanqcreport",
            name="al_ion",
            field=models.FloatField(blank=True, null=True, verbose_name="Al离子"),
        ),
        migrations.AlterField(
            model_name="dayuanqcreport",
            name="alkali_content",
            field=models.FloatField(blank=True, null=True, verbose_name="入窑前碱含量(%)"),
        ),
        migrations.AlterField(
            model_name="dayuanqcreport",
            name="bags",
            field=models.FloatField(blank=True, null=True, verbose_name="袋数"),
        ),
        migrations.AlterField(
            model_name="dayuanqcreport",
            name="brightness",
            field=models.FloatField(blank=True, null=True, verbose_name="白度"),
        ),
        migrations.AlterField(
            model_name="dayuanqcreport",
            name="ca_ion",
            field=models.FloatField(blank=True, null=True, verbose_name="Ca离子"),
        ),
        migrations.AlterField(
            model_name="dayuanqcreport",
            name="conductance",
            field=models.FloatField(blank=True, null=True, verbose_name="电导值(ms/cm)"),
        ),
        migrations.AlterField(
            model_name="dayuanqcreport",
            name="date",
            field=models.DateField(default=datetime.date.today, verbose_name="日期"),
        ),
        migrations.AlterField(
            model_name="dayuanqcreport",
            name="fe_ion",
            field=models.FloatField(blank=True, null=True, verbose_name="Fe离子"),
        ),
        migrations.AlterField(
            model_name="dayuanqcreport",
            name="flux",
            field=models.FloatField(blank=True, null=True, verbose_name="助溶剂添加比例"),
        ),
        migrations.AlterField(
            model_name="dayuanqcreport",
            name="moisture",
            field=models.FloatField(blank=True, null=True, verbose_name="水分(%)"),
        ),
        migrations.AlterField(
            model_name="dayuanqcreport",
            name="moisture_after_drying",
            field=models.FloatField(blank=True, null=True, verbose_name="干燥后原土水分(%)"),
        ),
        migrations.AlterField(
            model_name="dayuanqcreport",
            name="oil_absorption",
            field=models.FloatField(blank=True, null=True, verbose_name="吸油量"),
        ),
        migrations.AlterField(
            model_name="dayuanqcreport",
            name="permeability",
            field=models.FloatField(blank=True, null=True, verbose_name="远通渗透率(Darcy)"),
        ),
        migrations.AlterField(
            model_name="dayuanqcreport",
            name="permeability_long",
            field=models.FloatField(blank=True, null=True, verbose_name="长富渗透率(Darcy)"),
        ),
        migrations.AlterField(
            model_name="dayuanqcreport",
            name="ph",
            field=models.FloatField(blank=True, null=True, verbose_name="pH"),
        ),
        migrations.AlterField(
            model_name="dayuanqcreport",
            name="sieving_14m",
            field=models.FloatField(blank=True, null=True, verbose_name="+14M (%)"),
        ),
        migrations.AlterField(
            model_name="dayuanqcreport",
            name="sieving_150m",
            field=models.FloatField(blank=True, null=True, verbose_name="+150M (%)"),
        ),
        migrations.AlterField(
            model_name="dayuanqcreport",
            name="sieving_200m",
            field=models.FloatField(blank=True, null=True, verbose_name="+200M (%)"),
        ),
        migrations.AlterField(
            model_name="dayuanqcreport",
            name="sieving_30m",
            field=models.FloatField(blank=True, null=True, verbose_name="+30M (%)"),
        ),
        migrations.AlterField(
            model_name="dayuanqcreport",
            name="sieving_325m",
            field=models.FloatField(blank=True, null=True, verbose_name="+325M (%)"),
        ),
        migrations.AlterField(
            model_name="dayuanqcreport",
            name="sieving_40m",
            field=models.FloatField(blank=True, null=True, verbose_name="+40M (%)"),
        ),
        migrations.AlterField(
            model_name="dayuanqcreport",
            name="tons",
            field=models.FloatField(blank=True, null=True, verbose_name="吨"),
        ),
        migrations.AlterField(
            model_name="dayuanqcreport",
            name="water_absorption",
            field=models.FloatField(blank=True, null=True, verbose_name="吸水量"),
        ),
        migrations.AlterField(
            model_name="dayuanqcreport",
            name="wet_cake_density",
            field=models.FloatField(blank=True, null=True, verbose_name="饼密度(g/cm3)"),
        ),
        migrations.AlterModelTable(
            name="dayuanqcreport",
            table=None,
        ),
    ]
