# Generated by Django 5.1.6 on 2025-05-15 02:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0018_alter_dayuanqcreport_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dayuanqcreport",
            name="time",
            field=models.TimeField(default="00:00", verbose_name="时间"),
        ),
    ]
