# Generated by Django 5.1.6 on 2025-05-15 06:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0019_dayuanqcreport_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="dayuanqcreport",
            name="packaging",
            field=models.CharField(default="", max_length=50, verbose_name="包装类型"),
        ),
    ]
