# Generated by Django 5.1.6 on 2025-05-21 03:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0020_dayuanqcreport_packaging"),
    ]

    operations = [
        migrations.AddField(
            model_name="dayuanqcreport",
            name="batch_number",
            field=models.CharField(default="", max_length=50, verbose_name="批号"),
        ),
    ]
