# Generated by Django 5.1.6 on 2025-05-21 03:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0021_dayuanqcreport_batch_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="dayuanqcreport",
            name="swirl",
            field=models.FloatField(blank=True, null=True, verbose_name="涡值(cm)"),
        ),
    ]
