# Generated by Django 5.1.6 on 2025-05-24 08:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0022_dayuanqcreport_swirl"),
    ]

    operations = [
        migrations.CreateModel(
            name="Parameter",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        verbose_name="参数ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="参数名称")),
                ("value", models.CharField(max_length=500, verbose_name="参数值")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="参数描述"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "系统参数",
                "verbose_name_plural": "系统参数",
                "ordering": ["id"],
            },
        ),
    ]
