# Generated by Django 5.1.6 on 2025-05-24 08:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0023_add_parameter_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="parameter",
            name="group",
            field=models.CharField(default="默认分组", max_length=100, verbose_name="参数分组"),
        ),
    ]
