# Generated by Django 5.1.6 on 2025-05-26 06:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0024_add_group_to_parameter"),
    ]

    operations = [
        migrations.AddField(
            model_name="dayuanqcreport",
            name="odor",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="气味"
            ),
        ),
    ]
