# Generated by Django 4.2.10 on 2025-06-09 05:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0025_dayuanqcreport_odor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dongtaiqcreport',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': '东泰QC报表', 'verbose_name_plural': '东泰QC报表'},
        ),
        migrations.RemoveField(
            model_name='dongtaiqcreport',
            name='material_code',
        ),
        migrations.RemoveField(
            model_name='dongtaiqcreport',
            name='material_name',
        ),
        migrations.RemoveField(
            model_name='dongtaiqcreport',
            name='remark',
        ),
        migrations.RemoveField(
            model_name='dongtaiqcreport',
            name='test_item',
        ),
        migrations.RemoveField(
            model_name='dongtaiqcreport',
            name='test_result',
        ),
        migrations.RemoveField(
            model_name='dongtaiqcreport',
            name='tester',
        ),
        migrations.AddField(
            model_name='dongtaiqcreport',
            name='alkali_content_before_kiln',
            field=models.FloatField(blank=True, null=True, verbose_name='入窑前碱含量(%)'),
        ),
        migrations.AddField(
            model_name='dongtaiqcreport',
            name='bag_count',
            field=models.FloatField(blank=True, null=True, verbose_name='袋数'),
        ),
        migrations.AddField(
            model_name='dongtaiqcreport',
            name='bulk_density',
            field=models.FloatField(blank=True, null=True, verbose_name='振实密度(g/cm3)'),
        ),
        migrations.AddField(
            model_name='dongtaiqcreport',
            name='cake_density',
            field=models.FloatField(blank=True, null=True, verbose_name='饼密度(g/cm3)'),
        ),
        migrations.AddField(
            model_name='dongtaiqcreport',
            name='changfu_permeability',
            field=models.FloatField(blank=True, null=True, verbose_name='长富渗透率(Darcy)'),
        ),
        migrations.AddField(
            model_name='dongtaiqcreport',
            name='conductivity',
            field=models.FloatField(blank=True, null=True, verbose_name='电导值(ms/cm)'),
        ),
        migrations.AddField(
            model_name='dongtaiqcreport',
            name='dry_soil_moisture',
            field=models.FloatField(blank=True, null=True, verbose_name='干后原土水分(%)'),
        ),
        migrations.AddField(
            model_name='dongtaiqcreport',
            name='eddy_value',
            field=models.FloatField(blank=True, null=True, verbose_name='涡值(cm)'),
        ),
        migrations.AddField(
            model_name='dongtaiqcreport',
            name='flux_additive_ratio',
            field=models.FloatField(blank=True, null=True, verbose_name='助溶剂添加比例'),
        ),
        migrations.AddField(
            model_name='dongtaiqcreport',
            name='mesh_150m',
            field=models.FloatField(blank=True, null=True, verbose_name='+150M'),
        ),
        migrations.AddField(
            model_name='dongtaiqcreport',
            name='mesh_325m',
            field=models.FloatField(blank=True, null=True, verbose_name='+325M'),
        ),
        migrations.AddField(
            model_name='dongtaiqcreport',
            name='mesh_40m',
            field=models.FloatField(blank=True, null=True, verbose_name='+40M'),
        ),
        migrations.AddField(
            model_name='dongtaiqcreport',
            name='mesh_80m',
            field=models.FloatField(blank=True, null=True, verbose_name='+80M'),
        ),
        migrations.AddField(
            model_name='dongtaiqcreport',
            name='odor',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='气味'),
        ),
        migrations.AddField(
            model_name='dongtaiqcreport',
            name='packaging_type',
            field=models.CharField(default='', max_length=50, verbose_name='包装类型'),
        ),
        migrations.AddField(
            model_name='dongtaiqcreport',
            name='ph',
            field=models.FloatField(blank=True, null=True, verbose_name='pH'),
        ),
        migrations.AddField(
            model_name='dongtaiqcreport',
            name='product_model',
            field=models.CharField(default='', max_length=100, verbose_name='产品型号'),
        ),
        migrations.AddField(
            model_name='dongtaiqcreport',
            name='remarks',
            field=models.TextField(blank=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='dongtaiqcreport',
            name='shift_group',
            field=models.CharField(default='', max_length=50, verbose_name='班组'),
        ),
        migrations.AddField(
            model_name='dongtaiqcreport',
            name='time',
            field=models.TimeField(default='00:00', verbose_name='时间'),
        ),
        migrations.AddField(
            model_name='dongtaiqcreport',
            name='tonnage',
            field=models.FloatField(blank=True, null=True, verbose_name='吨'),
        ),
        migrations.AddField(
            model_name='dongtaiqcreport',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dongtai_reports', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='dongtaiqcreport',
            name='username',
            field=models.CharField(max_length=150, null=True, verbose_name='用户名'),
        ),
        migrations.AddField(
            model_name='dongtaiqcreport',
            name='whiteness',
            field=models.FloatField(blank=True, null=True, verbose_name='白度'),
        ),
        migrations.AddField(
            model_name='dongtaiqcreport',
            name='yuantong_permeability',
            field=models.FloatField(blank=True, null=True, verbose_name='远通渗透率(Darcy)'),
        ),
        migrations.AlterField(
            model_name='dongtaiqcreport',
            name='batch_number',
            field=models.CharField(default='', max_length=50, verbose_name='批号'),
        ),
        migrations.AlterField(
            model_name='dongtaiqcreport',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='日期'),
        ),
    ]
