# Generated by Django 4.2.10 on 2025-06-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_alter_dongtaiqcreport_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayuanqcreport',
            name='sieving_80m',
            field=models.FloatField(blank=True, null=True, verbose_name='+80M (%)'),
        ),
    ]
