# Generated by Django 4.2.10 on 2025-06-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_dayuanqcreport_sieving_80m'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayuanqcreport',
            name='bulk_density',
            field=models.FloatField(blank=True, null=True, verbose_name='振实密度(g/cm3)'),
        ),
    ] 