# Generated by Django 4.2.10 on 2025-06-13 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_dayuanqcreport_bulk_density'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dongtaiqcreport',
            old_name='alkali_content_before_kiln',
            new_name='alkali_content',
        ),
        migrations.RenameField(
            model_name='dongtaiqcreport',
            old_name='bag_count',
            new_name='bags',
        ),
        migrations.RenameField(
            model_name='dongtaiqcreport',
            old_name='whiteness',
            new_name='brightness',
        ),
        migrations.RenameField(
            model_name='dongtaiqcreport',
            old_name='conductivity',
            new_name='conductance',
        ),
        migrations.RenameField(
            model_name='dongtaiqcreport',
            old_name='flux_additive_ratio',
            new_name='flux',
        ),
        migrations.RenameField(
            model_name='dongtaiqcreport',
            old_name='packaging_type',
            new_name='packaging',
        ),
        migrations.RenameField(
            model_name='dongtaiqcreport',
            old_name='yuantong_permeability',
            new_name='permeability',
        ),
        migrations.RenameField(
            model_name='dongtaiqcreport',
            old_name='changfu_permeability',
            new_name='permeability_long',
        ),
        migrations.RenameField(
            model_name='dongtaiqcreport',
            old_name='eddy_value',
            new_name='swirl',
        ),
        migrations.RenameField(
            model_name='dongtaiqcreport',
            old_name='tonnage',
            new_name='tons',
        ),
        migrations.RenameField(
            model_name='dongtaiqcreport',
            old_name='cake_density',
            new_name='wet_cake_density',
        ),
        migrations.RemoveField(
            model_name='dongtaiqcreport',
            name='dry_soil_moisture',
        ),
        migrations.RemoveField(
            model_name='dongtaiqcreport',
            name='mesh_150m',
        ),
        migrations.RemoveField(
            model_name='dongtaiqcreport',
            name='mesh_325m',
        ),
        migrations.RemoveField(
            model_name='dongtaiqcreport',
            name='mesh_40m',
        ),
        migrations.RemoveField(
            model_name='dongtaiqcreport',
            name='mesh_80m',
        ),
        migrations.RemoveField(
            model_name='dongtaiqcreport',
            name='product_model',
        ),
        migrations.RemoveField(
            model_name='dongtaiqcreport',
            name='shift_group',
        ),
        migrations.AddField(
            model_name='dongtaiqcreport',
            name='al_ion',
            field=models.FloatField(blank=True, null=True, verbose_name='Al离子'),
        ),
        migrations.AddField(
            model_name='dongtaiqcreport',
            name='ca_ion',
            field=models.FloatField(blank=True, null=True, verbose_name='Ca离子'),
        ),
        migrations.AddField(
            model_name='dongtaiqcreport',
            name='fe_ion',
            field=models.FloatField(blank=True, null=True, verbose_name='Fe离子'),
        ),
        migrations.AddField(
            model_name='dongtaiqcreport',
            name='moisture',
            field=models.FloatField(blank=True, null=True, verbose_name='水分(%)'),
        ),
        migrations.AddField(
            model_name='dongtaiqcreport',
            name='moisture_after_drying',
            field=models.FloatField(blank=True, null=True, verbose_name='干燥后原土水分(%)'),
        ),
        migrations.AddField(
            model_name='dongtaiqcreport',
            name='oil_absorption',
            field=models.FloatField(blank=True, null=True, verbose_name='吸油量'),
        ),
        migrations.AddField(
            model_name='dongtaiqcreport',
            name='product_name',
            field=models.CharField(default='', max_length=100, verbose_name='产品名称'),
        ),
        migrations.AddField(
            model_name='dongtaiqcreport',
            name='shift',
            field=models.CharField(default='', max_length=10, verbose_name='班次'),
        ),
        migrations.AddField(
            model_name='dongtaiqcreport',
            name='sieving_14m',
            field=models.FloatField(blank=True, null=True, verbose_name='+14M (%)'),
        ),
        migrations.AddField(
            model_name='dongtaiqcreport',
            name='sieving_150m',
            field=models.FloatField(blank=True, null=True, verbose_name='+150M (%)'),
        ),
        migrations.AddField(
            model_name='dongtaiqcreport',
            name='sieving_200m',
            field=models.FloatField(blank=True, null=True, verbose_name='+200M (%)'),
        ),
        migrations.AddField(
            model_name='dongtaiqcreport',
            name='sieving_30m',
            field=models.FloatField(blank=True, null=True, verbose_name='+30M (%)'),
        ),
        migrations.AddField(
            model_name='dongtaiqcreport',
            name='sieving_325m',
            field=models.FloatField(blank=True, null=True, verbose_name='+325M (%)'),
        ),
        migrations.AddField(
            model_name='dongtaiqcreport',
            name='sieving_40m',
            field=models.FloatField(blank=True, null=True, verbose_name='+40M (%)'),
        ),
        migrations.AddField(
            model_name='dongtaiqcreport',
            name='sieving_80m',
            field=models.FloatField(blank=True, null=True, verbose_name='+80M (%)'),
        ),
        migrations.AddField(
            model_name='dongtaiqcreport',
            name='water_absorption',
            field=models.FloatField(blank=True, null=True, verbose_name='吸水量'),
        ),
        migrations.AlterModelTable(
            name='dongtaiqcreport',
            table=None,
        ),
    ]
