# Generated by Django 4.2.10 on 2025-07-24 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_yuantong2qcreport_xinghui2qcreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='changfuqcreport',
            name='cake_thickness',
            field=models.FloatField(blank=True, null=True, verbose_name='饼厚(mm)'),
        ),
        migrations.AddField(
            model_name='changfuqcreport',
            name='filter_time',
            field=models.FloatField(blank=True, null=True, verbose_name='过滤时间(秒)'),
        ),
        migrations.AddField(
            model_name='changfuqcreport',
            name='water_viscosity',
            field=models.FloatField(blank=True, null=True, verbose_name='水黏度(mPa.s)'),
        ),
        migrations.AddField(
            model_name='dongtaiqcreport',
            name='cake_thickness',
            field=models.FloatField(blank=True, null=True, verbose_name='饼厚(mm)'),
        ),
        migrations.AddField(
            model_name='dongtaiqcreport',
            name='changfu_cake_density',
            field=models.FloatField(blank=True, null=True, verbose_name='长富饼密度(g/cm3)'),
        ),
        migrations.AddField(
            model_name='dongtaiqcreport',
            name='dongtai_filter_area',
            field=models.FloatField(blank=True, null=True, verbose_name='东泰过滤面积'),
        ),
        migrations.AddField(
            model_name='dongtaiqcreport',
            name='dongtai_permeability_coefficient',
            field=models.FloatField(blank=True, null=True, verbose_name='东泰渗透率系数'),
        ),
        migrations.AddField(
            model_name='dongtaiqcreport',
            name='dongtai_sample_weight',
            field=models.FloatField(blank=True, null=True, verbose_name='东泰样品重量'),
        ),
        migrations.AddField(
            model_name='dongtaiqcreport',
            name='filter_time',
            field=models.FloatField(blank=True, null=True, verbose_name='过滤时间(秒)'),
        ),
        migrations.AddField(
            model_name='dongtaiqcreport',
            name='material_type',
            field=models.CharField(choices=[('助熔煅烧品', '助熔煅烧品'), ('煅烧品', '煅烧品')], default='助熔煅烧品', max_length=50, verbose_name='物料类型'),
        ),
        migrations.AddField(
            model_name='dongtaiqcreport',
            name='water_viscosity',
            field=models.FloatField(blank=True, null=True, verbose_name='水黏度(mPa.s)'),
        ),
        migrations.AddField(
            model_name='dongtaiqcreport',
            name='yuantong_cake_density',
            field=models.FloatField(blank=True, null=True, verbose_name='远通饼密度(g/cm3)'),
        ),
        migrations.AddField(
            model_name='xinghui2qcreport',
            name='cake_thickness',
            field=models.FloatField(blank=True, null=True, verbose_name='饼厚(mm)'),
        ),
        migrations.AddField(
            model_name='xinghui2qcreport',
            name='filter_time',
            field=models.FloatField(blank=True, null=True, verbose_name='过滤时间(秒)'),
        ),
        migrations.AddField(
            model_name='xinghui2qcreport',
            name='water_viscosity',
            field=models.FloatField(blank=True, null=True, verbose_name='水黏度(mPa.s)'),
        ),
        migrations.AddField(
            model_name='xinghui2qcreport',
            name='xinghui_permeability',
            field=models.FloatField(blank=True, null=True, verbose_name='兴辉渗透率(Darcy)'),
        ),
        migrations.AddField(
            model_name='xinghuiqcreport',
            name='cake_thickness',
            field=models.FloatField(blank=True, null=True, verbose_name='饼厚(mm)'),
        ),
        migrations.AddField(
            model_name='xinghuiqcreport',
            name='filter_time',
            field=models.FloatField(blank=True, null=True, verbose_name='过滤时间(秒)'),
        ),
        migrations.AddField(
            model_name='xinghuiqcreport',
            name='water_viscosity',
            field=models.FloatField(blank=True, null=True, verbose_name='水黏度(mPa.s)'),
        ),
        migrations.AddField(
            model_name='xinghuiqcreport',
            name='xinghui_permeability',
            field=models.FloatField(blank=True, null=True, verbose_name='兴辉渗透率(Darcy)'),
        ),
        migrations.AddField(
            model_name='yuantong2qcreport',
            name='cake_thickness',
            field=models.FloatField(blank=True, null=True, verbose_name='饼厚(mm)'),
        ),
        migrations.AddField(
            model_name='yuantong2qcreport',
            name='changfu_cake_density',
            field=models.FloatField(blank=True, null=True, verbose_name='长富饼密度(g/cm3)'),
        ),
        migrations.AddField(
            model_name='yuantong2qcreport',
            name='filter_time',
            field=models.FloatField(blank=True, null=True, verbose_name='过滤时间(秒)'),
        ),
        migrations.AddField(
            model_name='yuantong2qcreport',
            name='material_type',
            field=models.CharField(choices=[('助熔煅烧品', '助熔煅烧品'), ('煅烧品', '煅烧品')], default='助熔煅烧品', max_length=50, verbose_name='物料类型'),
        ),
        migrations.AddField(
            model_name='yuantong2qcreport',
            name='water_viscosity',
            field=models.FloatField(blank=True, null=True, verbose_name='水黏度(mPa.s)'),
        ),
        migrations.AddField(
            model_name='yuantong2qcreport',
            name='yuantong_cake_density',
            field=models.FloatField(blank=True, null=True, verbose_name='远通饼密度(g/cm3)'),
        ),
        migrations.AddField(
            model_name='yuantong2qcreport',
            name='yuantong_filter_area',
            field=models.FloatField(blank=True, null=True, verbose_name='远通过滤面积'),
        ),
        migrations.AddField(
            model_name='yuantong2qcreport',
            name='yuantong_permeability_coefficient',
            field=models.FloatField(blank=True, null=True, verbose_name='远通渗透率系数'),
        ),
        migrations.AddField(
            model_name='yuantong2qcreport',
            name='yuantong_sample_weight',
            field=models.FloatField(blank=True, null=True, verbose_name='远通样品重量'),
        ),
        migrations.AddField(
            model_name='yuantongqcreport',
            name='cake_thickness',
            field=models.FloatField(blank=True, null=True, verbose_name='饼厚(mm)'),
        ),
        migrations.AddField(
            model_name='yuantongqcreport',
            name='changfu_cake_density',
            field=models.FloatField(blank=True, null=True, verbose_name='长富饼密度(g/cm3)'),
        ),
        migrations.AddField(
            model_name='yuantongqcreport',
            name='filter_time',
            field=models.FloatField(blank=True, null=True, verbose_name='过滤时间(秒)'),
        ),
        migrations.AddField(
            model_name='yuantongqcreport',
            name='material_type',
            field=models.CharField(choices=[('助熔煅烧品', '助熔煅烧品'), ('煅烧品', '煅烧品')], default='助熔煅烧品', max_length=50, verbose_name='物料类型'),
        ),
        migrations.AddField(
            model_name='yuantongqcreport',
            name='water_viscosity',
            field=models.FloatField(blank=True, null=True, verbose_name='水黏度(mPa.s)'),
        ),
        migrations.AddField(
            model_name='yuantongqcreport',
            name='yuantong_cake_density',
            field=models.FloatField(blank=True, null=True, verbose_name='远通饼密度(g/cm3)'),
        ),
        migrations.AddField(
            model_name='yuantongqcreport',
            name='yuantong_filter_area',
            field=models.FloatField(blank=True, null=True, verbose_name='远通过滤面积'),
        ),
        migrations.AddField(
            model_name='yuantongqcreport',
            name='yuantong_permeability_coefficient',
            field=models.FloatField(blank=True, null=True, verbose_name='远通渗透率系数'),
        ),
        migrations.AddField(
            model_name='yuantongqcreport',
            name='yuantong_sample_weight',
            field=models.FloatField(blank=True, null=True, verbose_name='远通样品重量'),
        ),
        migrations.AlterField(
            model_name='changfuqcreport',
            name='odor',
            field=models.FloatField(blank=True, null=True, verbose_name='气味'),
        ),
        migrations.AlterField(
            model_name='dayuanqcreport',
            name='odor',
            field=models.FloatField(blank=True, null=True, verbose_name='气味'),
        ),
        migrations.AlterField(
            model_name='dongtaiqcreport',
            name='odor',
            field=models.FloatField(blank=True, null=True, verbose_name='气味'),
        ),
        migrations.AlterField(
            model_name='xinghui2qcreport',
            name='odor',
            field=models.FloatField(blank=True, null=True, verbose_name='气味'),
        ),
        migrations.AlterField(
            model_name='xinghuiqcreport',
            name='odor',
            field=models.FloatField(blank=True, null=True, verbose_name='气味'),
        ),
        migrations.AlterField(
            model_name='yuantong2qcreport',
            name='odor',
            field=models.FloatField(blank=True, null=True, verbose_name='气味'),
        ),
        migrations.AlterField(
            model_name='yuantongqcreport',
            name='odor',
            field=models.FloatField(blank=True, null=True, verbose_name='气味'),
        ),
    ]
