# Generated by Django 4.2.10 on 2025-08-09 10:23

from django.db import migrations
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_changfuqcreport_cake_thickness_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changfuqcreport',
            name='odor',
            field=home.models.NullableFloatField(blank=True, null=True, verbose_name='气味'),
        ),
        migrations.AlterField(
            model_name='dayuanqcreport',
            name='odor',
            field=home.models.NullableFloatField(blank=True, null=True, verbose_name='气味'),
        ),
        migrations.AlterField(
            model_name='dongtaiqcreport',
            name='odor',
            field=home.models.NullableFloatField(blank=True, null=True, verbose_name='气味'),
        ),
        migrations.AlterField(
            model_name='xinghui2qcreport',
            name='odor',
            field=home.models.NullableFloatField(blank=True, null=True, verbose_name='气味'),
        ),
        migrations.AlterField(
            model_name='xinghuiqcreport',
            name='odor',
            field=home.models.NullableFloatField(blank=True, null=True, verbose_name='气味'),
        ),
        migrations.AlterField(
            model_name='yuantong2qcreport',
            name='odor',
            field=home.models.NullableFloatField(blank=True, null=True, verbose_name='气味'),
        ),
        migrations.AlterField(
            model_name='yuantongqcreport',
            name='odor',
            field=home.models.NullableFloatField(blank=True, null=True, verbose_name='气味'),
        ),
    ]
