# Generated by Django 4.2.10 on 2025-08-21 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_alter_changfuqcreport_odor_alter_dayuanqcreport_odor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changfuqcreport',
            name='water_viscosity',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='水黏度(mPa.s)'),
        ),
        migrations.AlterField(
            model_name='dongtaiqcreport',
            name='water_viscosity',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='水黏度(mPa.s)'),
        ),
        migrations.AlterField(
            model_name='xinghui2qcreport',
            name='water_viscosity',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='水黏度(mPa.s)'),
        ),
        migrations.AlterField(
            model_name='xinghuiqcreport',
            name='water_viscosity',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='水黏度(mPa.s)'),
        ),
        migrations.AlterField(
            model_name='yuantong2qcreport',
            name='water_viscosity',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='水黏度(mPa.s)'),
        ),
        migrations.AlterField(
            model_name='yuantongqcreport',
            name='water_viscosity',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='水黏度(mPa.s)'),
        ),
    ]
