# Generated by Django 4.2.10 on 2025-08-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_update_water_viscosity_precision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changfuqcreport',
            name='flux',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='助溶剂添加比例'),
        ),
        migrations.AlterField(
            model_name='dayuanqcreport',
            name='flux',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='助溶剂添加比例'),
        ),
        migrations.AlterField(
            model_name='dongtaiqcreport',
            name='flux',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='助溶剂添加比例'),
        ),
        migrations.AlterField(
            model_name='xinghui2qcreport',
            name='flux',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='助溶剂添加比例'),
        ),
        migrations.AlterField(
            model_name='xinghuiqcreport',
            name='flux',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='助溶剂添加比例'),
        ),
        migrations.AlterField(
            model_name='yuantong2qcreport',
            name='flux',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='助溶剂添加比例'),
        ),
        migrations.AlterField(
            model_name='yuantongqcreport',
            name='flux',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='助溶剂添加比例'),
        ),
    ]
