# Generated by Django 4.2.10 on 2025-08-28 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0040_update_flux_field_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='用户名')),
                ('operation_type', models.CharField(choices=[('CREATE', '创建'), ('UPDATE', '更新'), ('DELETE', '删除'), ('VIEW', '查看'), ('EXPORT', '导出'), ('LOGIN', '登录'), ('LOGOUT', '登出')], max_length=20, verbose_name='操作类型')),
                ('report_type', models.CharField(choices=[('dongtai', '东泰QC报表'), ('yuantong', '远通QC报表'), ('yuantong2', '远通2号QC报表'), ('dayuan', '大塬QC报表'), ('changfu', '长富QC报表'), ('xinghui', '兴辉QC报表'), ('xinghui2', '兴辉2号QC报表'), ('other', '其他')], max_length=20, verbose_name='报表类型')),
                ('report_id', models.IntegerField(blank=True, null=True, verbose_name='报表ID')),
                ('report_date', models.DateField(blank=True, null=True, verbose_name='报表日期')),
                ('operation_detail', models.TextField(blank=True, verbose_name='操作详情')),
                ('old_data', models.JSONField(blank=True, null=True, verbose_name='操作前数据')),
                ('new_data', models.JSONField(blank=True, null=True, verbose_name='操作后数据')),
                ('changed_fields', models.JSONField(blank=True, null=True, verbose_name='变更字段')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, verbose_name='用户代理')),
                ('request_path', models.CharField(blank=True, max_length=500, verbose_name='请求路径')),
                ('request_method', models.CharField(blank=True, max_length=10, verbose_name='请求方法')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作用户')),
            ],
            options={
                'verbose_name': '用户操作日志',
                'verbose_name_plural': '用户操作日志',
                'db_table': 'user_operation_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'operation_type', 'created_at'], name='user_operat_user_id_5fcd13_idx'), models.Index(fields=['report_type', 'operation_type', 'created_at'], name='user_operat_report__9b4698_idx'), models.Index(fields=['username', 'created_at'], name='user_operat_usernam_643e61_idx'), models.Index(fields=['report_id', 'report_type'], name='user_operat_report__93f24a_idx')],
            },
        ),
    ]
