# Generated by Django 4.2.10 on 2025-08-28 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_add_operation_log'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='useroperationlog',
            name='user_operat_user_id_5fcd13_idx',
        ),
        migrations.RemoveIndex(
            model_name='useroperationlog',
            name='user_operat_report__9b4698_idx',
        ),
        migrations.RemoveIndex(
            model_name='useroperationlog',
            name='user_operat_report__93f24a_idx',
        ),
        migrations.RemoveField(
            model_name='useroperationlog',
            name='changed_fields',
        ),
        migrations.RemoveField(
            model_name='useroperationlog',
            name='report_date',
        ),
        migrations.AlterField(
            model_name='useroperationlog',
            name='new_data',
            field=models.JSONField(blank=True, null=True, verbose_name='新数据'),
        ),
        migrations.AlterField(
            model_name='useroperationlog',
            name='old_data',
            field=models.JSONField(blank=True, null=True, verbose_name='旧数据'),
        ),
        migrations.AlterField(
            model_name='useroperationlog',
            name='report_type',
            field=models.CharField(blank=True, choices=[('dongtai', '东泰QC报表'), ('yuantong', '远通QC报表'), ('yuantong2', '远通2号QC报表'), ('dayuan', '大塬QC报表'), ('changfu', '长富QC报表'), ('xinghui', '兴辉QC报表'), ('xinghui2', '兴辉2号QC报表')], max_length=20, null=True, verbose_name='报表类型'),
        ),
        migrations.AlterField(
            model_name='useroperationlog',
            name='request_method',
            field=models.CharField(max_length=10, verbose_name='请求方法'),
        ),
        migrations.AlterField(
            model_name='useroperationlog',
            name='request_path',
            field=models.CharField(max_length=500, verbose_name='请求路径'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='useroperationlog',
            index=models.Index(fields=['user', 'created_at'], name='user_operat_user_id_bf83bf_idx'),
        ),
        migrations.AddIndex(
            model_name='useroperationlog',
            index=models.Index(fields=['operation_type', 'created_at'], name='user_operat_operati_a1036d_idx'),
        ),
        migrations.AddIndex(
            model_name='useroperationlog',
            index=models.Index(fields=['report_type', 'created_at'], name='user_operat_report__4ef664_idx'),
        ),
    ]
