# Generated by Django 4.2.10 on 2025-08-31 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_remove_useroperationlog_user_operat_user_id_5fcd13_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dongtaiqcreport',
            name='swirl',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='涡值(cm)'),
        ),
    ]
