# Generated by Django 4.2.10 on 2025-08-31 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_change_dongtai_swirl_to_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changfuqcreport',
            name='tons',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='吨'),
        ),
    ]
