# Generated by Django 4.2.10 on 2025-09-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_change_changfu_tons_to_decimal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayuanqcreport',
            name='tons',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='吨'),
        ),
        migrations.AlterField(
            model_name='dongtaiqcreport',
            name='tons',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='吨'),
        ),
        migrations.AlterField(
            model_name='xinghui2qcreport',
            name='tons',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='吨'),
        ),
        migrations.AlterField(
            model_name='xinghuiqcreport',
            name='tons',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='吨'),
        ),
        migrations.AlterField(
            model_name='yuantong2qcreport',
            name='tons',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='吨'),
        ),
        migrations.AlterField(
            model_name='yuantongqcreport',
            name='tons',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='吨'),
        ),
    ]
