# Generated by Django 4.2.10 on 2025-09-29 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_change_yuantong_tons_to_decimal'),
    ]

    operations = [
        migrations.AddField(
            model_name='changfuqcreport',
            name='sieving_100m',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='+100M (%)'),
        ),
        migrations.AddField(
            model_name='dayuanqcreport',
            name='sieving_100m',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='+100M (%)'),
        ),
        migrations.AddField(
            model_name='dongtaiqcreport',
            name='sieving_100m',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='+100M (%)'),
        ),
        migrations.AddField(
            model_name='xinghui2qcreport',
            name='sieving_100m',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='+100M (%)'),
        ),
        migrations.AddField(
            model_name='xinghuiqcreport',
            name='sieving_100m',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='+100M (%)'),
        ),
        migrations.AddField(
            model_name='yuantong2qcreport',
            name='sieving_100m',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='+100M (%)'),
        ),
        migrations.AddField(
            model_name='yuantongqcreport',
            name='sieving_100m',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='+100M (%)'),
        ),
    ]
