# Generated by Django 4.2.10 on 2025-10-10 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_changfuqcreport_sieving_100m_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dongtaiqcreport',
            name='tons',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='吨'),
        ),
    ]
