# Generated by Django 4.2.10 on 2025-10-10 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_update_dongtai_tons_precision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dongtaiqcreport',
            name='tons',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True, blank=True, verbose_name='吨'),
        ),
    ]
