# Generated by Django 4.2.10 on 2026-03-01 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_update_dongtai_tons_precision_to_3'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawSoilStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fnumber', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='单据编号')),
                ('biz_date', models.DateField(verbose_name='业务日期')),
                ('material_code', models.CharField(max_length=50, verbose_name='物料编码')),
                ('material_name', models.CharField(max_length=100, verbose_name='物料名称')),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='入库数量')),
                ('actual_quantity', models.DecimalField(decimal_places=4, default=0, help_text='入库数量*(1-扣水率)', max_digits=18, verbose_name='真实入库数量')),
                ('lot', models.CharField(blank=True, default='', max_length=100, verbose_name='批次号')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('cost_center_code', models.CharField(max_length=50, verbose_name='成本中心编码')),
                ('storage_org_code', models.CharField(max_length=50, verbose_name='库存组织编码')),
                ('warehouse_code', models.CharField(max_length=50, verbose_name='仓库编码')),
                ('cost_object_code', models.CharField(max_length=50, verbose_name='成本对象编码')),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='扣水率')),
                ('created_by', models.CharField(max_length=50, verbose_name='创建人')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '原土入库记录',
                'verbose_name_plural': '原土入库记录',
                'db_table': 'raw_soil_storage',
                'ordering': ['-biz_date', '-created_at'],
            },
        ),
    ]
