# Generated by Django 4.2.10 on 2025-10-20 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100, verbose_name='任务名称')),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失败'), ('running', '执行中')], max_length=20, verbose_name='执行状态')),
                ('message', models.TextField(blank=True, verbose_name='执行消息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('execution_time', models.FloatField(blank=True, null=True, verbose_name='执行时间(秒)')),
            ],
            options={
                'verbose_name': '任务日志',
                'verbose_name_plural': '任务日志',
                'ordering': ['-created_at'],
            },
        ),
    ]
