# Generated by Django 4.2.10 on 2025-10-20 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QCReportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('dayuan', '大塬QC报表'), ('dongtai', '东泰QC报表'), ('changfu', '长富QC报表'), ('xinghui', '兴辉QC报表'), ('xinghui2', '兴辉二线QC报表'), ('yuantong', '远通QC报表'), ('yuantong2', '远通二线QC报表')], max_length=20, unique=True, verbose_name='报表类型')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('send_hour', models.IntegerField(default=8, help_text='24小时制，0-23', verbose_name='发送小时')),
                ('send_minute', models.IntegerField(default=0, help_text='0-59', verbose_name='发送分钟')),
                ('recipient_userid', models.CharField(help_text='企业微信用户ID', max_length=100, verbose_name='接收人UserID')),
                ('recipient_name', models.CharField(help_text='接收人显示名称', max_length=100, verbose_name='接收人姓名')),
                ('send_excel', models.BooleanField(default=True, verbose_name='发送Excel文件')),
                ('send_text', models.BooleanField(default=True, verbose_name='发送文本消息')),
                ('text_template', models.TextField(blank=True, help_text='留空使用默认模板', verbose_name='文本消息模板')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': 'QC报表定时发送配置',
                'verbose_name_plural': 'QC报表定时发送配置',
                'ordering': ['report_type'],
            },
        ),
    ]
