# Generated by Django 4.2.10 on 2025-10-21 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_qcreportschedule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qcreportschedule',
            options={'ordering': ['report_type', 'recipient_name'], 'verbose_name': 'QC报表定时发送配置', 'verbose_name_plural': 'QC报表定时发送配置'},
        ),
        migrations.AlterField(
            model_name='qcreportschedule',
            name='report_type',
            field=models.CharField(choices=[('dayuan', '大塬QC报表'), ('dongtai', '东泰QC报表'), ('changfu', '长富QC报表'), ('xinghui', '兴辉QC报表'), ('xinghui2', '兴辉二线QC报表'), ('yuantong', '远通QC报表'), ('yuantong2', '远通二线QC报表')], max_length=20, verbose_name='报表类型'),
        ),
        migrations.AlterUniqueTogether(
            name='qcreportschedule',
            unique_together={('report_type', 'recipient_userid')},
        ),
    ]
