# Generated by Django 4.2.10 on 2025-11-04 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0003_remove_report_type_unique_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='QianlimaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='默认配置', help_text='配置的显示名称', max_length=100, verbose_name='配置名称')),
                ('is_enabled', models.BooleanField(default=True, help_text='是否启用此配置', verbose_name='是否启用')),
                ('recipient_userid', models.CharField(help_text='企业微信用户ID，如：GaoBieKeLe', max_length=100, verbose_name='接收人UserID')),
                ('recipient_name', models.CharField(help_text='接收人显示名称', max_length=100, verbose_name='接收人姓名')),
                ('batch_size', models.IntegerField(default=30, help_text='每次发送多少条招标信息（建议10-30条）', verbose_name='每次发送条数')),
                ('max_batch_length', models.IntegerField(default=2000, help_text='每批消息的最大字符数（企业微信限制约2048）', verbose_name='每批消息最大长度')),
                ('send_hour', models.IntegerField(default=9, help_text='24小时制，0-23，用于定时发送', verbose_name='发送小时')),
                ('send_minute', models.IntegerField(default=0, help_text='0-59，用于定时发送', verbose_name='发送分钟')),
                ('keywords', models.CharField(blank=True, default='全部', help_text='搜索关键词，如：硅藻土、助滤剂等，留空表示全部', max_length=200, verbose_name='关键词')),
                ('area_ids', models.CharField(default='2703', help_text='地区ID，2703表示全国，多个用逗号分隔', max_length=50, verbose_name='地区ID')),
                ('auto_refresh_token', models.BooleanField(default=True, help_text='Token失效时是否自动刷新', verbose_name='自动刷新Token')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '乙方宝招标信息发送配置',
                'verbose_name_plural': '乙方宝招标信息发送配置',
                'ordering': ['-created_at'],
            },
        ),
    ]
