# Generated by Django 4.2.10 on 2025-11-04 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0004_add_qianlima_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='QianlimaSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='用于标识此配置的名称', max_length=100, verbose_name='配置名称')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('send_hour', models.IntegerField(default=9, help_text='24小时制，0-23', verbose_name='发送小时')),
                ('send_minute', models.IntegerField(default=0, help_text='0-59', verbose_name='发送分钟')),
                ('recipient_userid', models.CharField(help_text='企业微信用户ID', max_length=100, verbose_name='接收人UserID')),
                ('recipient_name', models.CharField(help_text='接收人显示名称', max_length=100, verbose_name='接收人姓名')),
                ('batch_size', models.IntegerField(default=0, help_text='0表示发送全部，>0表示只发送前N条', verbose_name='发送条数')),
                ('max_batch_length', models.IntegerField(default=2000, help_text='企业微信消息长度限制，默认2000字符', verbose_name='每批消息最大长度')),
                ('keywords', models.CharField(blank=True, default='全部', help_text='搜索关键词，留空或"全部"表示不限制', max_length=200, verbose_name='关键词')),
                ('area_ids', models.CharField(blank=True, default='2703', help_text='地区ID，2703表示全国', max_length=50, verbose_name='地区ID')),
                ('auto_refresh_token', models.BooleanField(default=True, help_text='Token失效时自动尝试刷新', verbose_name='自动刷新Token')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '乙方宝招标信息定时发送配置',
                'verbose_name_plural': '乙方宝招标信息定时发送配置',
                'ordering': ['send_hour', 'send_minute', 'name'],
            },
        ),
        migrations.DeleteModel(
            name='QianlimaConfig',
        ),
    ]
