# Generated by Django 4.2.10 on 2025-11-04 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_add_qianlima_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qianlimaschedule',
            name='area_ids',
            field=models.CharField(default='2703', help_text='地区ID，2703表示全国', max_length=50, verbose_name='地区ID'),
        ),
        migrations.AlterField(
            model_name='qianlimaschedule',
            name='batch_size',
            field=models.IntegerField(default=0, help_text='0表示发送全部，>0表示限制发送条数', verbose_name='发送条数'),
        ),
        migrations.AlterField(
            model_name='qianlimaschedule',
            name='recipient_userid',
            field=models.CharField(help_text='企业微信用户ID，如：GaoBieKeLe', max_length=100, verbose_name='接收人UserID'),
        ),
    ]
