# Generated by Django 4.2.10 on 2025-11-04 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0006_add_qianlima_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='QianlimaMessageSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('send_hour', models.IntegerField(default=8, help_text='24小时制，0-23', verbose_name='发送小时')),
                ('send_minute', models.IntegerField(default=0, help_text='0-59', verbose_name='发送分钟')),
                ('recipient_userid', models.CharField(help_text='企业微信用户ID', max_length=100, verbose_name='接收人UserID')),
                ('recipient_name', models.CharField(help_text='接收人显示名称', max_length=100, verbose_name='接收人姓名')),
                ('message_count', models.IntegerField(default=10, help_text='每次发送的最大消息数量，0表示发送所有', verbose_name='发送消息数量')),
                ('send_text', models.BooleanField(default=True, verbose_name='发送文本消息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '千里马消息定时发送配置',
                'verbose_name_plural': '千里马消息定时发送配置',
                'ordering': ['recipient_name', 'send_hour', 'send_minute'],
            },
        ),
        migrations.CreateModel(
            name='QianlimaMessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='模板的显示名称', max_length=100, unique=True, verbose_name='模板名称')),
                ('template_content', models.TextField(help_text='\n支持以下变量替换：\n{{recipient_name}} - 收件人姓名\n{{recipient_userid}} - 收件人UserID\n{{total_messages}} - 本次获取的总消息数\n{{sent_messages}} - 发送给该用户的消息数\n{{sent_batches}} - 消息被分为多少批\n{{current_batch}} - 当前是第几批（仅在分批发送时有效）\n{{total_batches}} - 总批次数\n{{send_date}} - 发送日期 (YYYY-MM-DD)\n{{send_time}} - 发送时间 (HH:MM:SS)\n    ', verbose_name='模板内容')),
                ('is_default', models.BooleanField(default=False, help_text='设置为默认模板后，新建配置时会自动使用此模板', verbose_name='是否默认模板')),
                ('is_active', models.BooleanField(default=True, help_text='禁用后将无法选择此模板', verbose_name='是否启用')),
                ('description', models.TextField(blank=True, help_text='模板的用途和说明', verbose_name='模板描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '千里马消息模板',
                'verbose_name_plural': '千里马消息模板',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='QianlimaSendHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('recipient_userid', models.CharField(max_length=100, verbose_name='接收人UserID')),
                ('recipient_name', models.CharField(max_length=100, verbose_name='接收人姓名')),
                ('total_messages', models.IntegerField(default=0, help_text='本次发送的总招标信息数量', verbose_name='总消息数')),
                ('sent_messages', models.IntegerField(default=0, help_text='实际发送给该用户的消息数量', verbose_name='实际发送数')),
                ('sent_batches', models.IntegerField(default=0, help_text='消息被分为多少批发送', verbose_name='发送批次数')),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失败'), ('partial', '部分成功')], default='success', max_length=20, verbose_name='发送状态')),
                ('error_message', models.TextField(blank=True, help_text='发送失败时的错误信息', null=True, verbose_name='错误信息')),
                ('execution_time', models.FloatField(blank=True, help_text='发送过程耗时', null=True, verbose_name='执行时间(秒)')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('schedule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='send_histories', to='tasks.qianlimamessageschedule', verbose_name='发送配置')),
            ],
            options={
                'verbose_name': '千里马消息发送历史',
                'verbose_name_plural': '千里马消息发送历史',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.DeleteModel(
            name='QianlimaSchedule',
        ),
        migrations.AddField(
            model_name='qianlimamessageschedule',
            name='template',
            field=models.ForeignKey(blank=True, help_text='选择使用的消息模板，为空则使用默认模板', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.qianlimamessagetemplate', verbose_name='消息模板'),
        ),
        migrations.AddIndex(
            model_name='qianlimasendhistory',
            index=models.Index(fields=['sent_at'], name='tasks_qianl_sent_at_c8ecaa_idx'),
        ),
        migrations.AddIndex(
            model_name='qianlimasendhistory',
            index=models.Index(fields=['recipient_userid', 'sent_at'], name='tasks_qianl_recipie_1a9003_idx'),
        ),
        migrations.AddIndex(
            model_name='qianlimasendhistory',
            index=models.Index(fields=['status', 'sent_at'], name='tasks_qianl_status_56d69c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='qianlimamessageschedule',
            unique_together={('recipient_userid',)},
        ),
    ]
